/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package TokoSvc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Toko service. Represents a row in the &quot;master_Toko&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link TokoSvc.model.impl.TokoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TokoSvc.model.impl.TokoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Toko
 * @see TokoSvc.model.impl.TokoImpl
 * @see TokoSvc.model.impl.TokoModelImpl
 * @generated
 */
@ProviderType
public interface TokoModel extends BaseModel<Toko> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a toko model instance should use the {@link Toko} interface instead.
	 */

	/**
	 * Returns the primary key of this toko.
	 *
	 * @return the primary key of this toko
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this toko.
	 *
	 * @param primaryKey the primary key of this toko
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this toko.
	 *
	 * @return the uuid of this toko
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this toko.
	 *
	 * @param uuid the uuid of this toko
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the id_toko of this toko.
	 *
	 * @return the id_toko of this toko
	 */
	@AutoEscape
	public String getId_toko();

	/**
	 * Sets the id_toko of this toko.
	 *
	 * @param id_toko the id_toko of this toko
	 */
	public void setId_toko(String id_toko);

	/**
	 * Returns the nama_toko of this toko.
	 *
	 * @return the nama_toko of this toko
	 */
	@AutoEscape
	public String getNama_toko();

	/**
	 * Sets the nama_toko of this toko.
	 *
	 * @param nama_toko the nama_toko of this toko
	 */
	public void setNama_toko(String nama_toko);

	/**
	 * Returns the nama_depan_pemilik of this toko.
	 *
	 * @return the nama_depan_pemilik of this toko
	 */
	@AutoEscape
	public String getNama_depan_pemilik();

	/**
	 * Sets the nama_depan_pemilik of this toko.
	 *
	 * @param nama_depan_pemilik the nama_depan_pemilik of this toko
	 */
	public void setNama_depan_pemilik(String nama_depan_pemilik);

	/**
	 * Returns the nama_belakang_pemilik of this toko.
	 *
	 * @return the nama_belakang_pemilik of this toko
	 */
	@AutoEscape
	public String getNama_belakang_pemilik();

	/**
	 * Sets the nama_belakang_pemilik of this toko.
	 *
	 * @param nama_belakang_pemilik the nama_belakang_pemilik of this toko
	 */
	public void setNama_belakang_pemilik(String nama_belakang_pemilik);

	/**
	 * Returns the nomor_hp of this toko.
	 *
	 * @return the nomor_hp of this toko
	 */
	public long getNomor_hp();

	/**
	 * Sets the nomor_hp of this toko.
	 *
	 * @param nomor_hp the nomor_hp of this toko
	 */
	public void setNomor_hp(long nomor_hp);

	/**
	 * Returns the status_toko of this toko.
	 *
	 * @return the status_toko of this toko
	 */
	public long getStatus_toko();

	/**
	 * Sets the status_toko of this toko.
	 *
	 * @param status_toko the status_toko of this toko
	 */
	public void setStatus_toko(long status_toko);

	/**
	 * Returns the tanggal_pendaftaran of this toko.
	 *
	 * @return the tanggal_pendaftaran of this toko
	 */
	public Date getTanggal_pendaftaran();

	/**
	 * Sets the tanggal_pendaftaran of this toko.
	 *
	 * @param tanggal_pendaftaran the tanggal_pendaftaran of this toko
	 */
	public void setTanggal_pendaftaran(Date tanggal_pendaftaran);

	/**
	 * Returns the password of this toko.
	 *
	 * @return the password of this toko
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this toko.
	 *
	 * @param password the password of this toko
	 */
	public void setPassword(String password);

	/**
	 * Returns the pin of this toko.
	 *
	 * @return the pin of this toko
	 */
	public long getPin();

	/**
	 * Sets the pin of this toko.
	 *
	 * @param pin the pin of this toko
	 */
	public void setPin(long pin);

	/**
	 * Returns the id_distributor of this toko.
	 *
	 * @return the id_distributor of this toko
	 */
	@AutoEscape
	public String getId_distributor();

	/**
	 * Sets the id_distributor of this toko.
	 *
	 * @param id_distributor the id_distributor of this toko
	 */
	public void setId_distributor(String id_distributor);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Toko toko);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Toko> toCacheModel();

	@Override
	public Toko toEscapedModel();

	@Override
	public Toko toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}