/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package AlamatSvc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Alamat service. Represents a row in the &quot;master_Alamat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link AlamatSvc.model.impl.AlamatModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AlamatSvc.model.impl.AlamatImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Alamat
 * @see AlamatSvc.model.impl.AlamatImpl
 * @see AlamatSvc.model.impl.AlamatModelImpl
 * @generated
 */
@ProviderType
public interface AlamatModel extends BaseModel<Alamat> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a alamat model instance should use the {@link Alamat} interface instead.
	 */

	/**
	 * Returns the primary key of this alamat.
	 *
	 * @return the primary key of this alamat
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this alamat.
	 *
	 * @param primaryKey the primary key of this alamat
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this alamat.
	 *
	 * @return the uuid of this alamat
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this alamat.
	 *
	 * @param uuid the uuid of this alamat
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the id_alamat of this alamat.
	 *
	 * @return the id_alamat of this alamat
	 */
	@AutoEscape
	public String getId_alamat();

	/**
	 * Sets the id_alamat of this alamat.
	 *
	 * @param id_alamat the id_alamat of this alamat
	 */
	public void setId_alamat(String id_alamat);

	/**
	 * Returns the id_user of this alamat.
	 *
	 * @return the id_user of this alamat
	 */
	public long getId_user();

	/**
	 * Sets the id_user of this alamat.
	 *
	 * @param id_user the id_user of this alamat
	 */
	public void setId_user(long id_user);

	/**
	 * Returns the nama_alamat of this alamat.
	 *
	 * @return the nama_alamat of this alamat
	 */
	@AutoEscape
	public String getNama_alamat();

	/**
	 * Sets the nama_alamat of this alamat.
	 *
	 * @param nama_alamat the nama_alamat of this alamat
	 */
	public void setNama_alamat(String nama_alamat);

	/**
	 * Returns the nama_penerima of this alamat.
	 *
	 * @return the nama_penerima of this alamat
	 */
	@AutoEscape
	public String getNama_penerima();

	/**
	 * Sets the nama_penerima of this alamat.
	 *
	 * @param nama_penerima the nama_penerima of this alamat
	 */
	public void setNama_penerima(String nama_penerima);

	/**
	 * Returns the nomor_handphone of this alamat.
	 *
	 * @return the nomor_handphone of this alamat
	 */
	public long getNomor_handphone();

	/**
	 * Sets the nomor_handphone of this alamat.
	 *
	 * @param nomor_handphone the nomor_handphone of this alamat
	 */
	public void setNomor_handphone(long nomor_handphone);

	/**
	 * Returns the alamat_lengkap of this alamat.
	 *
	 * @return the alamat_lengkap of this alamat
	 */
	@AutoEscape
	public String getAlamat_lengkap();

	/**
	 * Sets the alamat_lengkap of this alamat.
	 *
	 * @param alamat_lengkap the alamat_lengkap of this alamat
	 */
	public void setAlamat_lengkap(String alamat_lengkap);

	/**
	 * Returns the kode_pos of this alamat.
	 *
	 * @return the kode_pos of this alamat
	 */
	public long getKode_pos();

	/**
	 * Sets the kode_pos of this alamat.
	 *
	 * @param kode_pos the kode_pos of this alamat
	 */
	public void setKode_pos(long kode_pos);

	/**
	 * Returns the kota of this alamat.
	 *
	 * @return the kota of this alamat
	 */
	@AutoEscape
	public String getKota();

	/**
	 * Sets the kota of this alamat.
	 *
	 * @param kota the kota of this alamat
	 */
	public void setKota(String kota);

	/**
	 * Returns the provinsi of this alamat.
	 *
	 * @return the provinsi of this alamat
	 */
	@AutoEscape
	public String getProvinsi();

	/**
	 * Sets the provinsi of this alamat.
	 *
	 * @param provinsi the provinsi of this alamat
	 */
	public void setProvinsi(String provinsi);

	/**
	 * Returns the region of this alamat.
	 *
	 * @return the region of this alamat
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this alamat.
	 *
	 * @param region the region of this alamat
	 */
	public void setRegion(String region);

	/**
	 * Returns the status of this alamat.
	 *
	 * @return the status of this alamat
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this alamat is status.
	 *
	 * @return <code>true</code> if this alamat is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this alamat is status.
	 *
	 * @param status the status of this alamat
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the created_date of this alamat.
	 *
	 * @return the created_date of this alamat
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this alamat.
	 *
	 * @param created_date the created_date of this alamat
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this alamat.
	 *
	 * @return the modified_date of this alamat
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this alamat.
	 *
	 * @param modified_date the modified_date of this alamat
	 */
	public void setModified_date(Date modified_date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Alamat alamat);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Alamat> toCacheModel();

	@Override
	public Alamat toEscapedModel();

	@Override
	public Alamat toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}