/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OrderSvc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Order service. Represents a row in the &quot;master_Order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link OrderSvc.model.impl.OrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrderSvc.model.impl.OrderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Order
 * @see OrderSvc.model.impl.OrderImpl
 * @see OrderSvc.model.impl.OrderModelImpl
 * @generated
 */
@ProviderType
public interface OrderModel extends BaseModel<Order> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order model instance should use the {@link Order} interface instead.
	 */

	/**
	 * Returns the primary key of this order.
	 *
	 * @return the primary key of this order
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this order.
	 *
	 * @param primaryKey the primary key of this order
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this order.
	 *
	 * @return the uuid of this order
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this order.
	 *
	 * @param uuid the uuid of this order
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the id_order of this order.
	 *
	 * @return the id_order of this order
	 */
	@AutoEscape
	public String getId_order();

	/**
	 * Sets the id_order of this order.
	 *
	 * @param id_order the id_order of this order
	 */
	public void setId_order(String id_order);

	/**
	 * Returns the total_harga of this order.
	 *
	 * @return the total_harga of this order
	 */
	public long getTotal_harga();

	/**
	 * Sets the total_harga of this order.
	 *
	 * @param total_harga the total_harga of this order
	 */
	public void setTotal_harga(long total_harga);

	/**
	 * Returns the tanggal_pemesanan of this order.
	 *
	 * @return the tanggal_pemesanan of this order
	 */
	public Date getTanggal_pemesanan();

	/**
	 * Sets the tanggal_pemesanan of this order.
	 *
	 * @param tanggal_pemesanan the tanggal_pemesanan of this order
	 */
	public void setTanggal_pemesanan(Date tanggal_pemesanan);

	/**
	 * Returns the tanggal_ekspetasi_pengiriman of this order.
	 *
	 * @return the tanggal_ekspetasi_pengiriman of this order
	 */
	public Date getTanggal_ekspetasi_pengiriman();

	/**
	 * Sets the tanggal_ekspetasi_pengiriman of this order.
	 *
	 * @param tanggal_ekspetasi_pengiriman the tanggal_ekspetasi_pengiriman of this order
	 */
	public void setTanggal_ekspetasi_pengiriman(
		Date tanggal_ekspetasi_pengiriman);

	/**
	 * Returns the status_order of this order.
	 *
	 * @return the status_order of this order
	 */
	@AutoEscape
	public String getStatus_order();

	/**
	 * Sets the status_order of this order.
	 *
	 * @param status_order the status_order of this order
	 */
	public void setStatus_order(String status_order);

	/**
	 * Returns the status_pembayaran_keseluruhan of this order.
	 *
	 * @return the status_pembayaran_keseluruhan of this order
	 */
	@AutoEscape
	public String getStatus_pembayaran_keseluruhan();

	/**
	 * Sets the status_pembayaran_keseluruhan of this order.
	 *
	 * @param status_pembayaran_keseluruhan the status_pembayaran_keseluruhan of this order
	 */
	public void setStatus_pembayaran_keseluruhan(
		String status_pembayaran_keseluruhan);

	/**
	 * Returns the status_pengiriman_keseluruhan of this order.
	 *
	 * @return the status_pengiriman_keseluruhan of this order
	 */
	@AutoEscape
	public String getStatus_pengiriman_keseluruhan();

	/**
	 * Sets the status_pengiriman_keseluruhan of this order.
	 *
	 * @param status_pengiriman_keseluruhan the status_pengiriman_keseluruhan of this order
	 */
	public void setStatus_pengiriman_keseluruhan(
		String status_pengiriman_keseluruhan);

	/**
	 * Returns the catatan of this order.
	 *
	 * @return the catatan of this order
	 */
	@AutoEscape
	public String getCatatan();

	/**
	 * Sets the catatan of this order.
	 *
	 * @param catatan the catatan of this order
	 */
	public void setCatatan(String catatan);

	/**
	 * Returns the create_date of this order.
	 *
	 * @return the create_date of this order
	 */
	public Date getCreate_date();

	/**
	 * Sets the create_date of this order.
	 *
	 * @param create_date the create_date of this order
	 */
	public void setCreate_date(Date create_date);

	/**
	 * Returns the modified_date of this order.
	 *
	 * @return the modified_date of this order
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this order.
	 *
	 * @param modified_date the modified_date of this order
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the id_metode_pembayaran of this order.
	 *
	 * @return the id_metode_pembayaran of this order
	 */
	@AutoEscape
	public String getId_metode_pembayaran();

	/**
	 * Sets the id_metode_pembayaran of this order.
	 *
	 * @param id_metode_pembayaran the id_metode_pembayaran of this order
	 */
	public void setId_metode_pembayaran(String id_metode_pembayaran);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Order order);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Order> toCacheModel();

	@Override
	public Order toEscapedModel();

	@Override
	public Order toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}