/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package UploadBuktiSpjSvc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Pengiriman service. Represents a row in the &quot;master_Pengiriman&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link UploadBuktiSpjSvc.model.impl.PengirimanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UploadBuktiSpjSvc.model.impl.PengirimanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pengiriman
 * @see UploadBuktiSpjSvc.model.impl.PengirimanImpl
 * @see UploadBuktiSpjSvc.model.impl.PengirimanModelImpl
 * @generated
 */
@ProviderType
public interface PengirimanModel extends BaseModel<Pengiriman> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pengiriman model instance should use the {@link Pengiriman} interface instead.
	 */

	/**
	 * Returns the primary key of this pengiriman.
	 *
	 * @return the primary key of this pengiriman
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this pengiriman.
	 *
	 * @param primaryKey the primary key of this pengiriman
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this pengiriman.
	 *
	 * @return the uuid of this pengiriman
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this pengiriman.
	 *
	 * @param uuid the uuid of this pengiriman
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the id_pengiriman of this pengiriman.
	 *
	 * @return the id_pengiriman of this pengiriman
	 */
	@AutoEscape
	public String getId_pengiriman();

	/**
	 * Sets the id_pengiriman of this pengiriman.
	 *
	 * @param id_pengiriman the id_pengiriman of this pengiriman
	 */
	public void setId_pengiriman(String id_pengiriman);

	/**
	 * Returns the tanggal_pengiriman of this pengiriman.
	 *
	 * @return the tanggal_pengiriman of this pengiriman
	 */
	public Date getTanggal_pengiriman();

	/**
	 * Sets the tanggal_pengiriman of this pengiriman.
	 *
	 * @param tanggal_pengiriman the tanggal_pengiriman of this pengiriman
	 */
	public void setTanggal_pengiriman(Date tanggal_pengiriman);

	/**
	 * Returns the status_pengiriman of this pengiriman.
	 *
	 * @return the status_pengiriman of this pengiriman
	 */
	@AutoEscape
	public String getStatus_pengiriman();

	/**
	 * Sets the status_pengiriman of this pengiriman.
	 *
	 * @param status_pengiriman the status_pengiriman of this pengiriman
	 */
	public void setStatus_pengiriman(String status_pengiriman);

	/**
	 * Returns the tanggal_penerimaan of this pengiriman.
	 *
	 * @return the tanggal_penerimaan of this pengiriman
	 */
	public Date getTanggal_penerimaan();

	/**
	 * Sets the tanggal_penerimaan of this pengiriman.
	 *
	 * @param tanggal_penerimaan the tanggal_penerimaan of this pengiriman
	 */
	public void setTanggal_penerimaan(Date tanggal_penerimaan);

	/**
	 * Returns the bukti_pengiriman of this pengiriman.
	 *
	 * @return the bukti_pengiriman of this pengiriman
	 */
	@AutoEscape
	public String getBukti_pengiriman();

	/**
	 * Sets the bukti_pengiriman of this pengiriman.
	 *
	 * @param bukti_pengiriman the bukti_pengiriman of this pengiriman
	 */
	public void setBukti_pengiriman(String bukti_pengiriman);

	/**
	 * Returns the create_date of this pengiriman.
	 *
	 * @return the create_date of this pengiriman
	 */
	public Date getCreate_date();

	/**
	 * Sets the create_date of this pengiriman.
	 *
	 * @param create_date the create_date of this pengiriman
	 */
	public void setCreate_date(Date create_date);

	/**
	 * Returns the modified_date of this pengiriman.
	 *
	 * @return the modified_date of this pengiriman
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this pengiriman.
	 *
	 * @param modified_date the modified_date of this pengiriman
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the id_order of this pengiriman.
	 *
	 * @return the id_order of this pengiriman
	 */
	@AutoEscape
	public String getId_order();

	/**
	 * Sets the id_order of this pengiriman.
	 *
	 * @param id_order the id_order of this pengiriman
	 */
	public void setId_order(String id_order);

	/**
	 * Returns the id_toko of this pengiriman.
	 *
	 * @return the id_toko of this pengiriman
	 */
	@AutoEscape
	public String getId_toko();

	/**
	 * Sets the id_toko of this pengiriman.
	 *
	 * @param id_toko the id_toko of this pengiriman
	 */
	public void setId_toko(String id_toko);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Pengiriman pengiriman);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Pengiriman> toCacheModel();

	@Override
	public Pengiriman toEscapedModel();

	@Override
	public Pengiriman toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}