/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ProdukSvc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Produk service. Represents a row in the &quot;master_Produk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ProdukSvc.model.impl.ProdukModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProdukSvc.model.impl.ProdukImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Produk
 * @see ProdukSvc.model.impl.ProdukImpl
 * @see ProdukSvc.model.impl.ProdukModelImpl
 * @generated
 */
@ProviderType
public interface ProdukModel extends BaseModel<Produk> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a produk model instance should use the {@link Produk} interface instead.
	 */

	/**
	 * Returns the primary key of this produk.
	 *
	 * @return the primary key of this produk
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this produk.
	 *
	 * @param primaryKey the primary key of this produk
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this produk.
	 *
	 * @return the uuid of this produk
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this produk.
	 *
	 * @param uuid the uuid of this produk
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the id_produk of this produk.
	 *
	 * @return the id_produk of this produk
	 */
	@AutoEscape
	public String getId_produk();

	/**
	 * Sets the id_produk of this produk.
	 *
	 * @param id_produk the id_produk of this produk
	 */
	public void setId_produk(String id_produk);

	/**
	 * Returns the create_date of this produk.
	 *
	 * @return the create_date of this produk
	 */
	public Date getCreate_date();

	/**
	 * Sets the create_date of this produk.
	 *
	 * @param create_date the create_date of this produk
	 */
	public void setCreate_date(Date create_date);

	/**
	 * Returns the modified_date of this produk.
	 *
	 * @return the modified_date of this produk
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this produk.
	 *
	 * @param modified_date the modified_date of this produk
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the nama_produk of this produk.
	 *
	 * @return the nama_produk of this produk
	 */
	@AutoEscape
	public String getNama_produk();

	/**
	 * Sets the nama_produk of this produk.
	 *
	 * @param nama_produk the nama_produk of this produk
	 */
	public void setNama_produk(String nama_produk);

	/**
	 * Returns the harga_produk of this produk.
	 *
	 * @return the harga_produk of this produk
	 */
	public long getHarga_produk();

	/**
	 * Sets the harga_produk of this produk.
	 *
	 * @param harga_produk the harga_produk of this produk
	 */
	public void setHarga_produk(long harga_produk);

	/**
	 * Returns the kelipatan_produk of this produk.
	 *
	 * @return the kelipatan_produk of this produk
	 */
	public long getKelipatan_produk();

	/**
	 * Sets the kelipatan_produk of this produk.
	 *
	 * @param kelipatan_produk the kelipatan_produk of this produk
	 */
	public void setKelipatan_produk(long kelipatan_produk);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Produk produk);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Produk> toCacheModel();

	@Override
	public Produk toEscapedModel();

	@Override
	public Produk toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}